### ISSUE TITLE
Configuration seems to be ignored

### ISSUE THREAD

**Issue by hunger** [rainbowhxch/beacon.nvim#1]
Thank you for this plugin, it works great out of the box!

I have a decently sized screen though and my eyesight is not that great, so I am trying to make the beacon bigger and show up more often. I use this packer config:

```lua
  use {
    "rainbowhxch/beacon.nvim",
    config = function()
      require('beacon').setup({
        size = 160,
        minimal_jump = 5,
      })
    end,
  }
```

The beacon did not change in size though nor does it show when jumping just 6 lines. Am I doing something wrong?

**Comment by hunger** [comment]
First issue! 🎉

**Comment by rainbowhxch** [comment]
> Thank you for this plugin, it works great out of the box!
> 
> I have a decently sized screen though and my eyesight is not that great, so I am trying to make the beacon bigger and show up more often. I use this packer config:
> 
> ```lua
>   use {
>     "rainbowhxch/beacon.nvim",
>     config = function()
>       require('beacon').setup({
>         size = 160,
>         minimal_jump = 5,
>       })
>     end,
>   }
> ```
> 
> The beacon did not change in size though nor does it show when jumping just 6 lines. Am I doing something wrong?

It's my carelessness. The default setup will overwrite the user setup. I just fixed it in aa4c68cda44005f7009b6847c40186fdd8541c94. You can try again.


> First issue! :tada:

And congratulations! :tada:

**Comment by akinsho** [comment]
Hey 👋🏿,

also trialling this plugin and liking it so far. I've just tried to disable it in certain buffers though where I find it distracting, but it seems that part of the config is also ignored. You might want to do a `vim.tbl_deep_extend` with the user config and the defaults to make sure user preferences overwrite the defaults.

**Comment by rainbowhxch** [comment]
> Hey 👋🏿,
> 
> also trialling this plugin and liking it so far. I've just tried to disable it in certain buffers though where I find it distracting, but it seems that part of the config is also ignored. You might want to do a `vim.tbl_deep_extend` with the user config and the defaults to make sure user preferences overwrite the defaults.

Hey, just fixed it and you can try again.

**Comment by akinsho** [comment]
Seems to be working now, thanks 👍🏾

**Comment by hunger** [comment]
Works like a charm now! Thank you!
