### ISSUE TITLE
Jumping from the Quickfix list highlights the wrong position

### ISSUE THREAD

**Issue by TheBlob42** [rainbowhxch/beacon.nvim#2]
Same error as in [beacon.nvim](https://github.com/DanilaMihailov/beacon.nvim) see [here](https://github.com/DanilaMihailov/beacon.nvim/issues/14)

When jumping to an entry of the Quickfix list, often the former cursor position is highlighted instead

This should be solvable by "scheduling" the highlight call (see my answer in the linked issue). I am currently on the go so I could not further look into this yet, but maybe you can already figure this out easily  :slightly_smiling_face:

**Comment by rainbowhxch** [comment]
Fixed it. Thanks for your feedback and solution. 

> but maybe you can already figure this out easily

When I understand neovim events more deeply, I will try to solve the problem fundamentally. :)

**Comment by rainbowhxch** [comment]
Just want you know, because #4 I deleted `vim.schedule()`, after using other cursor position acquisition methods, most of the jumps in quickfix are normal, but there are still some wrong highlights with a difference of one line that I can't solve.

**Comment by rainbowhxch** [comment]
> Just want you know, because #4 I deleted `vim.schedule()`, after using other cursor position acquisition methods, most of the jumps in quickfix are normal, but there are still some wrong highlights with a difference of one line that I can't solve.

Never mind. The conflict in #4 should not affect this issue. It will be rolled back.
