### ISSUE TITLE
Doesn't work with mini.session

### ISSUE THREAD

**Issue by edshamis** [rainbowhxch/beacon.nvim#3]
Throws error when loading a session with  [mini.session](https://github.com/echasnovski/mini.nvim#minisessions)
`
Error executing vim.schedule lua callback: ...ocal/share/nvim/plugged/beacon.nvim/lua/beacon/fader.lua:100: Invalid buffer id: 2
stack traceback:
        [C]: in function 'nvim_open_win'
        ...ocal/share/nvim/plugged/beacon.nvim/lua/beacon/fader.lua:100: in function 'h
ighlight_position'
        ...local/share/nvim/plugged/beacon.nvim/lua/beacon/init.lua:14: in function 'hi
ghlight_position'
        [string ":lua"]:1: in function <[string ":lua"]:1>
`

**Comment by rainbowhxch** [comment]
The reason is mini.session will wipe out all buffers when loading a session, including the hidden one used by beacon. I just added validity judgment. You can try again.

**Comment by edshamis** [comment]
Thanks! It's fixed
