### ISSUE TITLE
[Bug] Conflict with neorg capture buffers etc.

### ISSUE THREAD

**Issue by akinsho** [rainbowhxch/beacon.nvim#4]
<img width="1383" alt="Screen Shot 2022-05-04 at 09 05 44" src="https://user-images.githubusercontent.com/22454918/166636094-c11e6969-ad2b-48f7-9e2d-8da42ab2550d.png">

Whilst trying to open a capture buffer (`Neorg gtd capture`) whilst using [neorg](https://github.com/nvim-neorg/neorg) the error above is thrown about the window being closed immediately

**Comment by rainbowhxch** [comment]
Fixed it. But beacon.nvim will highlight a wrong position and the first `WinEnter` highlight can't be ignore even if ignore_buffers or ignore_filetypes is set. I think it's a conflict, but I can't find out the reason, and it may involve the event scheduling of neovim, so I'm not going to solve it. I'm sorry it affects your use, but I plan to add a switch option to control `WinEnter` event. If you have any other ideas, please let me know.

**Comment by rainbowhxch** [comment]
I checked the source code of neorg again, the issue caused by [clean up autocmd](https://github.com/nvim-neorg/neorg/blob/633dfc9f0c3a00a32ee89d4ab826da2eecfe9bd8/lua/neorg/modules/core/ui/module.lua#L155-L159) of the `capture popup`. So, this is a conflict, and adaptation cannot be made on this side. You should use `ignore_filetypes`/`ignore_buffers`, for example:
```lua
require('beacon').setup({
  ignore_filetypes = {'neorg'}
  -- or ignore_buffers = {'neorg://Quick Actions'}
})
```

I've tested again and `ignore_filetypes`/`ignore_buffers` work well, so never mind the last message. I will roll back this fix because it affects other issues.

**Comment by akinsho** [comment]
@rainbowhxch thanks for looking into it. I just tried `ignore_buffers = {'neorg://Quick Actions'}` and that seems to work fine 👍🏾

**Comment by akinsho** [comment]
@rainbowhxch so I've run into this issue with yet another type of `neorg` buffer it's quite blocking, and I'm wondering if there is any more general to handle this for example can I disable the plugin through an autocommand when I'm inside neorg buffers or can I use a regex like `ignore_buffers = {'neorg://*'}` or better still can you wrap the failing functions inside `pcall` so that it doesn't explode I really don't mind if it doesn't show the beacon inside neorg buffers, but this literally stops me from taking notes which is quite frustrating.

**Comment by rainbowhxch** [comment]
The ostrich strategy seem to make sence. I will wrap the functions inside `pcall`. Have you try `ignore_filetypes = {'neorg'}`, if it works, you can use it first and wait for me to fix this.

**Comment by akinsho** [comment]
@rainbowhxch I've tried with ignoring `neorg` as a filetype and that doesn't work, unfortunately.

**Comment by rainbowhxch** [comment]
Unfortunately, such conflict can still occur even though `pcall` is wraped. I think the only way is to disable beacon.nvim completely in the norg files. Try `vim.cmd [[autocmd BufReadPre *.norg lua require('beacon').beacon_off()]]`.

**Comment by rainbowhxch** [comment]
@akinsho Such conflict can still occur even though `pcall` is wraped, unfortunately. So i think the only way is to disable beacon.nvim completely in the norg files. Try `vim.cmd [[autocmd BufReadPre *.norg lua require('beacon').beacon_off()]]`.

**Comment by akinsho** [comment]
@rainbowhxch just tried the autocommand and that seems to work fine, thanks 👍🏾. I'm curious why the pcall still causes an error though (just actual curiosity, this solution is fine with me)

**Comment by rainbowhxch** [comment]
Beacon.nvim use a floating window to simulate cursor flashing (see [here](https://github.com/rainbowhxch/beacon.nvim/blob/main/lua/beacon/fader.lua#L79-L95)). And one feature of neorg buffer is that when user leaves the buffer, it will be automatically cleaned up (see [here](https://github.com/nvim-neorg/neorg/blob/main/lua/neorg/modules/core/ui/module.lua#L155-L159)). Therefore, after entering the neorg buffer using commands such as `Neorg gtd capture`, beacon.nvim will first open a floating window, which will trigger the cleanup of neorg buffer and it will become empty.

**Comment by rainbowhxch** [comment]
@akinsho Beacon.nvim use a floating window to simulate cursor flashing (see [here](https://github.com/rainbowhxch/beacon.nvim/blob/main/lua/beacon/fader.lua#L79-L95)). And one feature of neorg buffer is that when user leaves the buffer, it will be automatically cleaned up (see [here](https://github.com/nvim-neorg/neorg/blob/main/lua/neorg/modules/core/ui/module.lua#L155-L159)). Therefore, after entering the neorg buffer using commands such as `Neorg gtd capture`, beacon.nvim will first open a floating window, which will trigger the cleanup of neorg buffer and it will become empty. I can't find a good way to solve the conflict :(.
