### ISSUE TITLE
Directional feedback in the beacon

### ISSUE THREAD

**Issue by Alaz-Oz** [rainbowhxch/beacon.nvim#5]
What I was thinking is that, what if implement the fading effect from the direction which it is coming from, like if it is coming from line 1 to line 10 then fade vertically (i.e., top to bottom). This way it will be obvious from which direction (and place) the cursor is coming from, something like the neovide gui, but in the terminal.

**Comment by rainbowhxch** [comment]
@asteroidalaz Unfortunately, that style cannot be implemented because beacon uses `floating window` to implement fading effect which can only be rectangular.
