### ISSUE TITLE
require('beacon').setup() breaks it

### ISSUE THREAD

**Issue by ghost** [rainbowhxch/beacon.nvim#6]
hi,
i really wanna use this plugin but its a bit confusing, maybe im just configuring it wrong.

even just having require('beacon').setup() in my init.lua breaks beacon. it still does function but it doesnt change the background color to the lighter color. it still fades, just you cant see it pretty much.

**Comment by rainbowhxch** [comment]
@qube-03 Hi, I can't get the meaning of `it doesnt change the background color to the lighter color`, can you show a screenshot? And, if you feel the beacon own flashes too light, maybe `beacon highlight group` is your need, see [here](https://github.com/rainbowhxch/beacon.nvim#highlights).

**Comment by ghost** [comment]
maybe im goind insane, but this resolved itself just now. maybe it was a bug with the order in which i used require but its solved, i dont know why lol
