### ISSUE TITLE
Bug: report error when window width is too small

### ISSUE THREAD

**Issue by axieax** [rainbowhxch/beacon.nvim#8]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/62098008/203843593-8c78b707-f541-4909-94d2-03eed59f5d32.png">

I seem to occasionally get this error when opening aerial.nvim's panel. Perhaps it's to do with the width calculation of an opening buffer, but am not too sure. Beacon still works in the panel ignoring the error (maybe just a check to ensure width is set before continuing is enough?).

**Comment by rainbowhxch** [comment]
Yes, it's a width calculation error. I have reproduced and fixed it, which is triggered when the window width is 1. You can update beacon and check it.

**Comment by axieax** [comment]
Thanks!
